// This file is auto-generated by @hey-api/openapi-ts

export { backendInfoGet, type Options, stationsGet } from './sdk.gen';
export type {
  ApiTokenParam,
  BackendInfoGetData,
  BackendInfoGetResponse,
  BackendInfoGetResponses,
  ClientOptions,
  DateParam,
  Id,
  Platform,
  Station,
  StationParam,
  StationsGetData,
  StationsGetResponse,
  StationsGetResponses,
  StationsResponse,
  TimeTableInfo,
  Train,
  TrainInfoResponse,
  TrainNrParam,
} from './types.gen';
