/**
 * ÖBB Live Backend Info
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Station {
  /**
   * Unique station ID
   */
  eva?: string;
  /**
   * Station display name
   */
  name?: string;
}
