/**
 * ÖBB Live Backend Info
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TimeTableInfo {
  date?: string;
  platform?: string;
  renderedTrainName?: string;
  sector?: string;
  stationName?: string;
  time?: string;
}
