/**
 * ÖBB Live Backend Info
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TrainWagonsInner {
  capacityBicycle?: number;
  capacityBusinessClass?: number;
  capacityCouchette?: number;
  capacityFirstClass?: number;
  capacitySecondClass?: number;
  capacitySleeper?: number;
  capacityWheelChair?: number;
  destinationName?: string;
  features?: number;
  kind?: number;
  lengthOverBuffers?: number;
  /**
   * 1 (low), 2 (medium), 3 (high)
   */
  numPassengerIcons?: number;
  ranking?: number;
}
