/**
 * ÖBB Live Backend Info
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainWagonsInner } from './train-wagons-inner';

export interface Train {
  trainNr?: number;
  date?: string;
  version?: number;
  isReported?: boolean;
  assemblyStation?: string;
  source?: string;
  wagons?: Array<TrainWagonsInner>;
  stations?: Array<string>;
}
