/**
 * ÖBB Live Backend Info
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Platform } from './platform';
import { TimeTableInfo } from './time-table-info';
import { Train } from './train';

export interface TrainInfoResponse {
  id?: string;
  platform?: Platform;
  timeTableInfo?: TimeTableInfo;
  train?: Train;
}
