/**
 * ÖBB Live Backend Info
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
  HttpContext,
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { TrainInfoResponse } from '../model/train-info-response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

@Injectable({
  providedIn: 'root',
})
export class TrainService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration,
  ) {
    super(basePath, configuration);
  }

  /**
   * Live train data
   * @param apiToken
   * @param trainNr Unique per day train number (without the train type information)
   * @param date Date at which the train operates
   * @param station Unique station ID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public backendInfoGet(
    apiToken: string,
    trainNr: number,
    date: string,
    station: number,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<TrainInfoResponse>;
  public backendInfoGet(
    apiToken: string,
    trainNr: number,
    date: string,
    station: number,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpResponse<TrainInfoResponse>>;
  public backendInfoGet(
    apiToken: string,
    trainNr: number,
    date: string,
    station: number,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<HttpEvent<TrainInfoResponse>>;
  public backendInfoGet(
    apiToken: string,
    trainNr: number,
    date: string,
    station: number,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext; transferCache?: boolean },
  ): Observable<any> {
    if (apiToken === null || apiToken === undefined) {
      throw new Error('Required parameter apiToken was null or undefined when calling backendInfoGet.');
    }
    if (trainNr === null || trainNr === undefined) {
      throw new Error('Required parameter trainNr was null or undefined when calling backendInfoGet.');
    }
    if (date === null || date === undefined) {
      throw new Error('Required parameter date was null or undefined when calling backendInfoGet.');
    }
    if (station === null || station === undefined) {
      throw new Error('Required parameter station was null or undefined when calling backendInfoGet.');
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>trainNr, 'trainNr');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>date, 'date');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>station, 'station');

    let localVarHeaders = this.defaultHeaders;
    if (apiToken !== undefined && apiToken !== null) {
      localVarHeaders = localVarHeaders.set('api_token', String(apiToken));
    }

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/backend/info`;
    return this.httpClient.request<TrainInfoResponse>('get', `${this.configuration.basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      withCredentials: this.configuration.withCredentials,
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress,
    });
  }
}
